// import '../../lib/collections.js';
import './accounts/accounts-general';
import './methods/activities-methods';
import './methods/admin-methods';
import './methods/chat-methods';
import './methods/document-methods';
import './methods/email-methods';
import './methods/host-methods';
import './methods/image-upload';
import './methods/page-methods';
import './methods/process-methods';
import './methods/profile-methods';
import './methods/publish';
import './methods/resources-methods';
import './methods/shared';
import './methods/work-methods';